config/routes.rb
Events::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  
  match '/events/search' => 'events#search'
  match '/events/tag/:hashtag' => 'events#get_tag'
  match '/events/availability' => 'events#availability'  
  
  root :to => "stats#home"
  
  resources :events do
    member do
      post 'tag'      
    end
  end
  
  resources :photos

end

app/models/event.rb
class Event < ActiveRecord::Base
  # attr_accessible :title, :body
  
  belongs_to :owner_u1, class_name: "User", foreign_key: "owner"
  belongs_to :owner_u2, class_name: "User", foreign_key: "owner2"
  has_many :photos
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:new, :show, :search, :get_tag, :availability]
  
  def availability
    tag = params[:tag].delete "#"
    @result = Hash.new  
    in_arr = get_tag_instagram tag, {}
    if !in_arr.nil? && in_arr.length > 3
      @result[:instagram] = in_arr[0..2]
    end
    
    tw_arr = get_tag_twitter tag, {}
    if !tw_arr.nil? && tw_arr.length > 3
      @result[:twitter] = tw_arr[0..2]
    end
    
    respond_to do |format|
      format.js { render :json => @result.to_json }
    end    
  end
  
  def search
   search_term = params[:term].delete "#"
   @events = Event.search(search_term)
   
   respond_to do |format|
     format.js { render :json => @events.to_json}
   end 
  end
  
  def get_tag
    @event = Event.search(params[:hashtag]).first
    if !@event.nil?
      redirect_to event_path(@event)
    else 
      render 'new'      
    end
  end
   
  def create
    @event = Event.where("owner =? OR owner2 = ?", current_user.id, current_user.id)
    if @event.blank?
      @event = Event.new
      @event.owner = current_user.id
      @event.tag = params[:event][:tag].delete "#"
      if @event.save
        current_user.import
        redirect_to event_path(@event)
      else        
        render 'error'        
      end
    else
      redirect_to event_path(@event.first)          
    end        
  end
  
  def new
    @event ||= Event.new
    if !current_user.nil?
      event = Event.where("owner =? OR owner2 = ?", current_user.id, current_user.id)
      if !event.blank?
        redirect_to event_path(event.first)
      end     
    end
  end
  
  def show
    if !@event.nil? || !params[:id].nil?
      @event ||= Event.find_by_id(params[:id])
    end    
                          
    @page = params[:page] || 0
    if @page == 0
      params[:in_max_id] = nil
      params[:in_min_id] = nil
      params[:tw_max_id] = nil
      params[:tw_min_id] = nil
    end
    
    @result = Array.new
    if user_signed_in?
      current_user.import_photos_fb @event
      #fb_result = get_tag_info @event.tag, "fb"
    end
    
    @photos = @event.photos
        
    in_result = Array.new
    if !params[:in_max_id].nil?
      in_result = get_tag_instagram @event.tag, :max_id => params[:in_max_id]
    elsif !params[:in_min_id].nil?
      in_result = get_tag_instagram @event.tag, :min_id => params[:in_min_id]
    else
      if params[:tw_max_id].nil?
        in_result = get_tag_instagram @event.tag, {}
      end   
    end    
    
    in_result.each do |r|
      entry = Media.new
      entry.user = r.user.username
      entry.profile_img = r.user.profile_picture
      entry.created_at = Time.at(r.created_time.to_i)
      if r.type == "image"
        entry.media = r.images.standard_resolution.url
        entry.type = 1
      elsif r.type == "video"
        entry.media = r.videos.standard_resolution.url
        entry.thumb = r.images.standard_resolution.url
        entry.type = 0
      end
            
      @result << entry
    end
    
    if in_result.length > 0
      if !params[:in_max_id].nil?
        @in_min_id = in_result.pagination.min_tag_id
      end
      
      @in_max_id = in_result.pagination.next_max_tag_id
    end        
    
    tw_result = Array.new
    if !params[:tw_max_id].nil?
      tw_result = get_tag_twitter @event.tag, :max_id => params[:tw_max_id].to_i, :result_type => "mixed"
    elsif !params[:tw_min_id].nil?
       tw_result = get_tag_twitter @event.tag, :max_id => params[:tw_min_id].to_i, :result_type => "mixed"
    else
      if params[:in_max_id].nil?
        tw_result = get_tag_twitter @event.tag, {}
      end  
    end
    
    if tw_result.length > 0
      if !params[:tw_max_id].nil?
        @tw_min_id = tw_result[0].id
      end
       
      @tw_max_id = tw_result[tw_result.length - 1].id + 1 
    end
    
    tw_result.each do |r|
      entry = Media.new
      entry.oid = r.id
      entry.user = r.user.screen_name
      entry.profile_img = r.user.profile_image_url
      entry.created_at = r.created_at 
      entry.media = r.text
      entry.type = 2
      @result << entry
    end 
    
    @result = @result.sort_by { |x| x.created_at }.reverse   
  end
  
  def tag
    event = Event.where("id = ? and (owner = ? OR owner2 = ?)", params[:id], current_user.id, current_user.id).first
    if !event.blank?
      debugger
      event.tag = params[:tag]
      event.save
      
      render :nothing => true
    end
  end
   
  private
  def get_tag_info tag, provider
    result = ''
    
    if provider == "instagram"
      result = get_tag_instagram tag      
    elsif provider == "twitter"      
      @twitter_client ||= Twitter::Client.new(
        :consumer_key =>  'ROZrWFKHxJeBPnLmWyz4g',
        :consumer_secret => '8K7WY88iDffc8lEqyQsF9Qrw9iCEwoXAdZUz5WvGws'
       )    
            
      result = get_tag_twitter tag
    elsif provider == "fb"
      result = get_tag_fb tag
    end
    
    return result    
  end
    
  def get_tag_instagram tag, options = {}
    Instagram.tag_recent_media(tag, options)
  end
  
  def get_tag_twitter tag, options = {}
    tweets = Array.new    
    @twitter_client ||= Twitter::Client.new(
      :consumer_key =>  'ROZrWFKHxJeBPnLmWyz4g',
      :consumer_secret => '8K7WY88iDffc8lEqyQsF9Qrw9iCEwoXAdZUz5WvGws'
     )
    
    t_result = @twitter_client.search(tag, options)    
    t_result.results.map do |tweet|     
      tweets << tweet
    end
    
    return tweets
  end
  
  def get_tag_fb tag
    @graph = Koala::Facebook::GraphAPI.new(current_user.token)
    news = @graph.fql_query("SELECT post_id, actor_id, target_id, message FROM stream where filter_key IN (SELECT filter_key FROM stream_filter WHERE uid='#{current_user.uid}' AND type='newsfeed')")
    related_news = Array.new
    
    news.each do |item|
      if item.include? tag
        related_news << item
      end
    end
    
    news
  end  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/new.html.erb
<div class="container-fluid" style="overflow: hidden">
	<div class="row">
		<div id="left-pane" class="col-md-3 hidden-xs hidden-sm">
			<%  _img = Photo.get_image %>
			<img id="left-pane-img" src="<%= "/assets/" + _img[:name] %>" />
			<span class="glyphicon glyphicon-info-sign" style="color: white; left: 20px; top: 10px; position: absolute;" title="<%= _img[:attr] %>"></span>
		</div>
		<div id="right-pane" class="col-md-9" style="background: white;">
			<a class="btn btn-info pull-right" type="button" title="Home" href="<%= root_path %>" style="margin-right: 15px; margin-top: 15px">
				<span class="glyphicon glyphicon-home"></span>
			</a>			
			<% if current_user.nil? %>
				<div style="clear:both; text-align:center; padding-top: 22%; padding-bottom: 15px">
					<%= link_to "Sign in with Facebook", omniauth_authorize_path(:user, "facebook"), :class => "btn btn-primary btn-lg" %>
				</div>
				<div style="text-align: center;font-size: 16px; padding-top: 20px; padding-bottom: 15px">
					<span>We never post to Facebook</span>
				</div>
				<% if !@event.errors.blank? %>
					<div style="text-align: center;font-size: 16px; padding-top: 25px; padding-bottom: 15px; padding-left: 20px; padding-right: 20px;">
						<% if @event.errors.messages[:owner].include? "user_denied" %>
							<span>It looks like you have denied access to your facebook profile. Please reconsider providing access, we never post to your news feed or store any of your personal info on our site.</span>
						<% end %>
					</div>					
				<% end %>				
			<% else %>
				<div class="row">
					<div class="col-md-offset-2" >
						<img style="text-align: center; margin-top: 25px;" class="img-circle" src="https://graph.facebook.com/<%= current_user.uid %>/picture?width=50&height=50" />	
					</div>
					
					<div class="col-md-6 col-md-offset-2">
						<%= form_for @event, url: { action: "create"} , html: { role: "form", class: "form-horizontal" } do |f| %>
							<div class="row">
								<div class="col-xs-6" style="margin-left: 70px">
									<%= f.label "Choose your hashtag", :style => "margin-top: 15px;" %>
								</div>
							</div>						
							<div class="row">
								<div class="col-xs-10" style="margin-left: 70px">
									<%= f.text_field :tag, :class => "form-control", :style => "margin-top:15px;", :value => "#" %>
								</div>									
							</div>																					
							
							<div class="row">
								<div style="text-align: center">										
									<%= f.submit "Create", :id => "event-btn", :class => "btn btn-default btn-primary", :style => "margin-top:15px;", :disable_with => "Creating"%>
								</div>
							</div>
						<% end %>
					</div>
				</div>
				<div class="row" style="margin-top: 200px;">
					<div class="col-md-6 col-md-offset-2">
						<div style="text-align: center">
							<a href="/events/availability" id="a-check">Check if hashtag is used by others</a>
						</div>
					</div>
				</div>
				<div class="row" style="margin-top: 15px;">
					<div id="tweet-box" class="col-md-6" style="text-align: center">
						<div class="row">
							<span class="check-header" style="visibility: hidden; font-size: 1.2em">Twitter</span>
						</div>
						<div class="row" style="margin-top: 10px;">
							<div id="tw-holder" class="list-group"></div>
						</div>
					</div>
					<div id="insta-box" class="col-md-6" style="text-align: center">
						<div class="row">
							<span class="check-header" style="visibility: hidden; font-size: 1.2em">Instagram</span>
						</div>
						<div class="row" style="margin-top: 10px;">												
							<div id="in-holder" class="list-group"></div>
						</div>
					</div>
				</div>				
			<% end %>
		</div>
	</div>
</div>

<script type="text/javascript">
	function resizeColumn() {
		$('#left-pane-img').height($(window).height());
		$('#right-pane').css({ 'min-height': $(window).height() + 'px' });				
	};
	
	function checkTagAvailability() {
		if(validateTag()) {
			$('#tw-holder').empty();
			$('#in-holder').empty();
			
			$.getJSON("<%= events_availability_path %>", { tag: $('#event_tag').val() }, function(data){				
				var tweetBox = $('#tw-holder');
				var instaBox = $('#in-holder');
				if(data['instagram'] && data['instagram'].length > 0) {
					$.each(data['instagram'], function(i, item){
						var img = document.createElement('img');
						img.src = item.images.standard_resolution.url;
						img.style.height = "150px";
						img.style.width = "150px";
						instaBox.append(img);				
					});
				} else {
					instaBox.text('No photos tagged with your hashtag');
				}
	
				
				if(data['twitter'] && data['twitter'].length > 0) {			
					$.each(data['twitter'], function(i, item){
						var spanEl = document.createElement('span');
						spanEl.className = "list-group-item";
						$(spanEl).text(item.text);
						tweetBox.append(spanEl);				
					});			
				} else {
					tweetBox.text('No tweets with your hashtag');
				}
				
				$('.check-header').css('visibility', 'visible');
			}).fail(function(){
				alert("Failed to get data from instagram and twitter. Please try again later");
			});
		} else {
			
		}				
	};
	
	function validateTag() {
		var tagValue = $('#event_tag').val();	
		if(tagValue.length > 1) {
		   var iChars = "#!@$%^&*()+=-[]\\\';,./{}|\":<>?~_";
		   for (var i = 0; i < tagValue.length; i++) {
		   	if(tagValue.charAt(0) == '#') {
		   		continue;	
		   	}
		   	
		  	if (iChars.indexOf(tagValue.charAt(i)) != -1) {
		  	  alert ("Your hashtag has special characters. \nThese are not allowed.");
		  	  return false;
		  	}			  				  	
		  }
		  
		  return true;
		} else {
			alert("Enter a valid hashtag");
		}
		  return false;				
	};
	
	$(document).ready(function() {
		resizeColumn();
		$(window).resize(resizeColumn);
		
		$('#event_tag').focusout(function(){
			if(validateTag()) {			  
			  $('#event-btn').removeAttr('disabled');				
			} else {
			  $('#event-btn').attr('disabled', 'disabled');
			}
			
			
		});
		
		$('#a-check').click(function() {
			checkTagAvailability();
			return false;
		});		
	});
</script>

app/views/events/show.html.erb
<div class="container-fluid" style="overflow: hidden">
	<div class="row">
		<div class="col-md-3 hidden-xs" id="left-pane" >
			<div class="affix">
				<% if !@event.photos.nil? && @event.photos.length > 0  
					 index = rand(0..(@event.photos.length - 1))					 
				%>
						
					<img id="left-pane-img" src="<%= @event.photos[index].url %>" />
				<% else	
					  _img = Photo.get_image 
				%>
	   				<img id="left-pane-img" src="<%= "/assets/" + _img[:name] %>" />
	   				<span class="glyphicon glyphicon-info-sign" style="color: white; left: 10px; top: 10px; position: absolute;" title="<%= _img[:attr] %>"></span>									
				<% end %>
			</div>
		</div>
		<div id="right-pane" class="col-md-9" style="background: white;">			
           <div class="row" style="margin-right: 20px;">            		
				<div class="btn-group pull-right">
					<div id="loading" style="float: left; font-weight: normal; margin-right: 10px; color: red; margin-top: 10px"></div>
					<input id="tag-search" type="search" placeholder="Search by hastag" class="form-control" style="float: left; width: 150px; visibility: hidden; margin-right: 10px;"></input>
					<button id="search-btn" class="btn btn-warning" type="button" title="Search">
						<span class="glyphicon glyphicon-search"></span>
					</button>
					<a class="btn btn-info" type="button" title="Home" href="<%= root_path %>">
						<span class="glyphicon glyphicon-home"></span>
					</a>
					<% if current_user.nil? %>
						<a class="btn btn-success" title="Log in" href="<%= omniauth_authorize_path(:user, "facebook") %>">
							<span class="glyphicon glyphicon-log-in"></span>
						</a>					
					<% else %>						
						<a id="log-out-btn" class="btn btn-danger" type="button" title="Log out" data-remote="true" href="<%= destroy_user_session_path %>" data-method="delete">
							<span class="glyphicon glyphicon-log-out"></span>
						</a>
					<% end %>
				</div>
            </div>		
			<div class="row" style="margin-top: 30px">
				<div class="col-md-10 col-md-offset-1">
					<% if !@event.owner_u2.nil? %>
						<img style="text-align: center" class="img-circle pull-left" src="https://graph.facebook.com/<%= @event.owner_u2.uid %>/picture?width=50&height=50" />
					<% end %>
					<% if !@event.owner_u1.nil? %>
						<img style="text-align: center" class="img-circle pull-right" src="https://graph.facebook.com/<%= @event.owner_u1.uid %>/picture?width=50&height=50" />
					<% end %>																
				</div>
			</div>		
			<div class="row">
				<div class="col-md-10">
					<% if @result.length <= 0 %>
						<div class="row" style="padding-bottom: 35px; margin-left: 25%; margin-top: 75px">
						<% if @in_max_id.nil? && @tw_max_id.nil? %>							
								<span>No posts at this moment. Post to instagram or twitter with #<%= @event.tag %> and see them all here</span>							
						<% else %>
								<span>No more posts.</span>
						<% end %>
						</div>
					<% end %>
					<% @result.each do |item| %>
						<div class="row" style="padding-bottom: 35px; margin-left: 30%;">
							<% if item.type == 2 %>
								<div class="col-md-9" >		
									<div style="text-align: center">				
									<blockquote class="twitter-tweet"><p><%= item.media %></p>&mdash; <%= item.user %> <a href="https://twitter.com/<%=item.user%>/statuses/<%=item.oid%>">November 6, 2013</a></blockquote>
									</div>
								</div>
							<% end %>
							<% if item.type == 1 %>																
								<div class="col-md-9" style="padding-left: 0px; padding-right: 0px; margin-left: 20px;">
									<div class="instagram-block" style="max-width: 465px">
										<div class="row" style="margin-top: 5px; padding-left: 5px">
											<div class="col-md-2">
												<img src="<%= item.profile_img %>" class="img-circle" style="height: 50px; width: 50px"></img>											
											</div>
											<!--
											<div class="col-md-1 pull-right">
												<div class="pin-holder">
													<span class="glyphicon glyphicon-pushpin"></span>
												</div>
											</div>
											-->
										</div>									
										<div class="row" style="margin-top:10px; margin-left: 0px; margin-right: 0px">
											<div>
												<img src="<%= item.media %>" style="width: 100%; height: 470px; max-width: 470px;"></img>
											</div>
										</div>
									</div>																		
								</div>
							<% end %>
							<% if item.type == 0 %>																
								<div class="col-md-9 instagram-block" style="padding-left: 0px; padding-right: 0px">
									<div class="row" style="margin-top: 5px; padding-left: 5px">
										<div class="col-md-2">
											<img src="<%= item.profile_img %>" class="img-circle" style="height: 50px; width: 50px"></img>
										</div>
										<!--
										<div class="col-md-1 pull-right">
											<div class="pin-holder">
												<span class="glyphicon glyphicon-pushpin"></span>
											</div>
										</div>
										-->
									</div>									
									<div class="row" style="margin-top:10px; margin-left: 0px; margin-right: 0px">
										<div style="max-width: 465px">
											<video controls="controls" poster="<%= item.thumb %>" width="470" height="470">
												<source src="<%= item.media %>" type="video/mp4" />
											</video>
										</div>
									</div>																		
								</div>
							<% end %>							
						</div>														
					<% end %>
				</div>					
			</div>
			<div class="row" style="text-align: center; margin-top: 15px; padding-bottom: 15px;">
				<%
					prev_url = nil
					if !@in_min_id.nil?
					  prev_url = event_path(@event) + "?in_min_id=" + @in_min_id
					end
					
					if !@tw_min_id.nil?
					  if prev_url.nil?
					  	prev_url = event_path(@event) + '?tw_min_id=' + @tw_min_id.to_s
					  else
					  	prev_url = prev_url + '&tw_min_id=' + @tw_min_id.to_s
					  end
					end
				%>
				
				<% if !prev_url.blank? && @page.to_i != 0
					prev_url = prev_url + "&page=" + (@page.to_i - 1).to_s 
				%>
					<a href="<%= prev_url %>" class="btn btn-primary" style="margin-right: 25px">Prev Page</a>
				<% end %>
									
				<% 				
				   url = nil
				   if !@in_max_id.nil?
					 url = event_path(@event) + '?in_max_id=' + @in_max_id	
				   end 
				   
				   if !@tw_max_id.nil?				
				   	if url.nil?
				   	  	url = event_path(@event) + '?tw_max_id=' + @tw_max_id.to_s
				   	else
				   		url = url + '&tw_max_id=' + @tw_max_id.to_s	
				   	end	
				   end 
				%>				
								
				<% if !url.blank?
					url = url + "&page=" + (@page.to_i + 1).to_s 
				%>				
					<a href="<%= url %>" class="btn btn-primary">Next Page</a>
				<% end %>							
			</div>	
		</div>
	</div>
</div>
<script type="text/javascript">

	function logOut() {
		$.cookie("remember_user_token", null);	
	}
	
	function resizeColumn() {
		$('#left-pane-img').height($(window).height());
		$('#right-pane').css({ 'min-height': $(window).height() + 'px' });				
	};
	
	$(document).ready(function() {
		resizeColumn();
		$(window).resize(resizeColumn);
		<% if !current_user.blank? %>
			$('#log-out-btn').bind('ajax:success', function() {
				alert("Logged out");
			});
		<% end %>
		
		$('#search-btn').click(function(){
			$('#tag-search').css("visibility", "visible");			
		});
		
		window.query_cache = {};
	    $('#tag-search').typeahead({
	      source:function(query,process){
	          // if in cache use cached value, if don't wanto use cache remove this if statement
	          if(query_cache[query]){
        	      var results = query_cache[query].map(function(event) {
            	     return event.tag;
		          });	          	
	              process(results);
	              return;
	          }
	          if( typeof searching != "undefined") {
	              clearTimeout(searching);
	              process([]);
	          }
	          searching = setTimeout(function() {
	              return $.getJSON(
	                  "<%= events_search_path %>",
	                  { term:query },
	                  function(data){
	            	      var results = data.map(function(event) {
		            	     return event.tag;
        		          });

						  if(data.length <= 0) {
						  	$('#loading').text('No Results');	
						  } else {
						  	$('#loading').text('');	
						  }
						  
	                      // save result to cache, remove next line if you don't want to use cache
	                      query_cache[query] = data;
	                      // only search if stop typing for 300ms aka fast typers
	                      return process(results);
	                  }
	              ).fail(function(){
	              	$('#loading').text('Oops, search Unavailable');
	              });
	          }, 500); // 300 ms
	      },
	      
	      updater: function(item) {
	      	window.location.href = '/events/tag/' + item;
	      }
	    });		
	});
	
</script>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>